export interface eGov {
    begin: number;
    end: number;
    'DG Systems & Services_#': number;
    'DG Systems & Services_Flag': string;
    'DG Systems & Services_Code': string;
    'DG Systems & Services_Economy': string;
    'Country Data_Level': string;
    'Country Data_Population': number;
    'Digital Government_e-Government': string;
    'Digital Government_eSrv': number;
    'Digital Government_e-Services': string;
    "UN e-Gov Dev Index_eGov'20": number;
    "UN e-Gov Dev Index_EGDI'20": number;
    "UN e-Gov Dev Index_eOSI'20": number;
    "UN e-Gov Dev Index_eTII'20": number;
    "UN e-Gov Dev Index_eHCI'20": number;
    "UN e-Gov Dev Index_ePart'20": number;
    'UN e-Gov Dev Index_DG Yr': number;
    'Whole of Government_WoG': number;
    'Whole of Government_Whole of Gov URL': string;
    GovTech_GT: number;
    'GovTech_GovTech Institution': string;
    'GovTech_GovTech URL': string;
    GovTech_Type: string;
    'GovTech_GT Org': string;
    'GovTech_GT since': string;
    'GovTech_GT focus': string;
    'GovTech_Other GT Links': string;
    'GovTech Products and Services_e-Gov': string;
    'GovTech Products and Services_e-ID': string;
    'GovTech Products and Services_GSB': string;
    'GovTech Products and Services_e-Serv': string;
    'GovTech Products and Services_Innov': string;
    'GovTech Products and Services_Priv': string;
    'GovTech Products and Services_DTech': string;
    'GovTech Products and Services_OSS': string;
    'GovTech Products and Services_KSL': string;
    'Finance Ministry web site, Public Finance data, and FMIS links_MoF URL': string;
    'Finance Ministry web site, Public Finance data, and FMIS links_Org Name': string;
    'Finance Ministry web site, Public Finance data, and FMIS links_PF': number;
    'Finance Ministry web site, Public Finance data, and FMIS links_Budget Data URL': string;
    'Finance Ministry web site, Public Finance data, and FMIS links_MIS': number;
    'Finance Ministry web site, Public Finance data, and FMIS links_FMIS URL': string;
    'Financial Management Information System_FMIS / TS': string;
    'Financial Management Information System_FMIS Name': string;
    'Financial Management Information System_Tpl': string;
    'Financial Management Information System_Func': string;
    'Financial Management Information System_Status': number;
    'Financial Management Information System_Op Yr': number;
    'Financial Management Information System_Scope': string;
    'Financial Management Information System_Type': number;
    'Financial Management Information System_ASW': number;
    'Financial Management Information System_ASW Solution': string;
    'Financial Management Information System_Arch': string;
    'Treasury Single Account_Treasury website': string;
    'Treasury Single Account_Tre Yr': number;
    'Treasury Single Account_TSA website': string;
    'Treasury Single Account_TSA Yr': number;
    'Treasury Single Account_TSA Type': number;
    'Treasury Single Account_TSA Scope': number;
    'Treasury Single Account_Duration': string;
    'Treasury Single Account_TSA Benefits': string;
    'Treasury Single Account_TSA Savings': string;
    'Treasury Single Account_Sav Yr': string;
    'Tax Administration_Tax Adm URL': string;
    'Tax Administration_Tax Yr': number;
    'Tax Administration_TMIS Abbr': string;
    'Tax Administration_TMIS Name': string;
    'Tax Administration_TMIS': number;
    'Tax Administration_TMIS Soln': string;
    'Tax Administration_Tax System URL': string;
    'Tax Administration_TMIS Yr': number;
    'Tax Administration_TMIS Sta': number;
    'Tax Administration_Tax Srv': number;
    'Customs Administration_Customs URL': string;
    'Customs Administration_Cust Yr': number;
    'Customs Administration_WCO Mem': number;
    'Customs Administration_HS Sta': number;
    'Customs Administration_Customs Abbr': string;
    'Customs Administration_Customs Name': string;
    'Customs Administration_CMIS': number;
    'Customs Administration_CMIS Soln': string;
    'Customs Administration_Customs Sys URL': string;
    'Customs Administration_CMIS Yr': number;
    'Customs Administration_Cust Sta': number;
    'Customs Administration_Cust Srv': number;
    'e-Filing_e-Filing URL': string;
    'e-Filing_eFil Yr': number;
    'e-Filing_eFil Srv': number;
    'e-Payment_ePayment': string;
    'e-Payment_ePay Yr': string;
    'e-Payment_ePay Srv': number;
    'Digital Signature_Digital Sign URL': string;
    'Digital Signature_Dsign Yr': string;
    'Digital Signature_Dsign Sta': number;
    'Public Employment_Public Emp': number;
    'Public Employment_PE Scope': number;
    'Public Employment_Pub Emp URL': string;
    'Public Employment_PE Yr': number;
    'HRMIS_HRMIS Abbr': string;
    'HRMIS_HRMIS System': string;
    HRMIS_HRM: number;
    'HRMIS_HRMIS Soln': string;
    'HRMIS_HRMIS URL': string;
    'HRMIS_HRM Yr': number;
    'HRMIS_HRM Sta': number;
    'HRMIS_HRM Srv': number;
    'Payroll System_Payroll Abbr': string;
    'Payroll System_Payroll System': string;
    'Payroll System_Payr': number;
    'Payroll System_Payr Soln': string;
    'Payroll System_Payroll URL': string;
    'Payroll System_Payr Yr': string;
    'Payroll System_Payr Sta': number;
    'Payroll System_Payr Srv': number;
    'e-Procurement_eProc System': string;
    'e-Procurement_eProcurement': string;
    'e-Procurement_ePrc Yr': number;
    'e-Procurement_ePrc Sta': number;
    'e-Procurement_ePr Srv': number;
    'e-Procurement_Contr Monitoring': string;
    'Public Debt_Debt Org / URL': string;
    'Public Debt_DMS': number;
    'Public Debt_DMS Soln': string;
    'Public Debt_DMS Yr': number;
    'Public Debt_DMS Sta': number;
    'Public Debt_DM Inst': string;
    'Public Debt_DM OpSt': string;
    'Public Investment Management Systems_PIM Unit URL': string;
    'Public Investment Management Systems_PIM Unit Name': string;
    'Public Investment Management Systems_WB PIR': string;
    'Public Investment Management Systems_WB PIR URL': string;
    'Public Investment Management Systems_PIMA': string;
    'Public Investment Management Systems_PIMS Abbr': string;
    'Public Investment Management Systems_PIMS Name': string;
    'Public Investment Management Systems_PIMS': number;
    'Public Investment Management Systems_PIMS Soln': string;
    'Public Investment Management Systems_PIMS URL': string;
    'Public Investment Management Systems_PIMS Yr': string;
    'Public Investment Management Systems_PIMS Sta': number;
    'Public Investment Management Systems_PIMS Fun': number;
    'Aid Mgmt Systems_AMP': string;
    'Aid Mgmt Systems_DAD': string;
    'Aid Mgmt Systems_Other': string;
    'Other Categories_Region': string;
    'Other Categories_FCS': number;
    'Other Categories_NRR': number;
    'Other Categories_Select': number;
    'Other Categories_Zone': string;
    'Other Categories_OECD': string;
    'Other Categories_APEC': string;
    'Other Categories_LenCat': string;
    'Data Governance Maturity_Grp': string;
    'Data Governance Maturity_DGM': number;
    'Data Governance Maturity_Pol&Reg': number;
    'Data Governance Maturity_Inst': number;
    'Data Governance Maturity_Infra': number;
    'Data Governance Institution, Policy & Regulations_Inst': number;
    'Data Governance Institution, Policy & Regulations_Inst Yr': string;
    'Data Governance Institution, Policy & Regulations_DGov Inst Name': string;
    'Data Governance Institution, Policy & Regulations_DGov Inst URL': string;
    'Data Governance Institution, Policy & Regulations_Type': number;
    'Data Governance Institution, Policy & Regulations_Impl': string;
    'Data Governance Institution, Policy & Regulations_Policy': number;
    'Data Governance Institution, Policy & Regulations_Pol Yr': string;
    'Data Governance Institution, Policy & Regulations_DG Policy URL': string;
    'Data Governance Institution, Policy & Regulations_Regs': number;
    'Data Governance Institution, Policy & Regulations_Reg Yr': string;
    'Data Governance Institution, Policy & Regulations_DG Regs URL': string;
    'Government Cloud, Enterprise Architecture and Interoperability Platform_GCL': number;
    'Government Cloud, Enterprise Architecture and Interoperability Platform_GCL Yr': string;
    'Government Cloud, Enterprise Architecture and Interoperability Platform_Gov Cloud Name': string;
    'Government Cloud, Enterprise Architecture and Interoperability Platform_Gov Cloud URL': string;
    'Government Cloud, Enterprise Architecture and Interoperability Platform_GEA': number;
    'Government Cloud, Enterprise Architecture and Interoperability Platform_GEA Yr': string;
    'Government Cloud, Enterprise Architecture and Interoperability Platform_GEA Name': string;
    'Government Cloud, Enterprise Architecture and Interoperability Platform_GEA URL': string;
    'Government Cloud, Enterprise Architecture and Interoperability Platform_GSB': number;
    'Government Cloud, Enterprise Architecture and Interoperability Platform_GSB Yr': string;
    'Government Cloud, Enterprise Architecture and Interoperability Platform_Interop Platform': string;
    'Government Cloud, Enterprise Architecture and Interoperability Platform_Interop URL': string;
    'National CERT or CSIRT_Cyber': number;
    'National CERT or CSIRT_Cyb Yr': number;
    'National CERT or CSIRT_Cybersecurity Agency': string;
    'National CERT or CSIRT_Cybersecurity URL': string;
    'National website for citizen participation_Part': number;
    'National website for citizen participation_Participation URL': string;
    'National website for citizen participation_Petit': number;
    'National website for citizen participation_Publ': number;
    'National website for citizen participation_Anym': number;
    'National website for citizen participation_Resp': number;
    'National website for citizen feedback / GRM_GRM': number;
    'National website for citizen feedback / GRM_GRM URL': string;
    'National website for citizen feedback / GRM_Serv': number;
    'National website for citizen feedback / GRM_Acce': number;
    'Government responsiveness_Perf': number;
    'Government responsiveness_Perf URL': string;
    'Legal System Type_Legal System Type': string;
    'Legal System Type_Leg Sys': number;
    'Data Protection & Privacy Laws_DPL': number;
    'Data Protection & Privacy Laws_DP Act / Bill': string;
    'Data Protection & Privacy Laws_Act/Bill URL': string;
    'Data Protection & Privacy Laws_From': string;
    'Data Protection & Privacy Laws_Latest': string;
    'Data Protection Agency_DPA': number;
    'Data Protection Agency_Data Protection Agency (DPA)': string;
    'Data Protection Agency_DPA URL': string;
    'Data Protection Agency_DPA Yr': string;
    'Right to Information Law_RTI': number;
    'Right to Information Law_Law URL': string;
    'Right to Information Law_Law Yr': number;
    'Is there an Open Government initiative?_OGI': number;
    'Is there an Open Government initiative?_Open Gov URL': string;
    'Is there an Open Data portal?_ODP': number;
    'Is there an Open Data portal?_Open Data URL': string;
    'Disruptive Technologies_DT': number;
    'Disruptive Technologies_DT Fo': string;
    'Disruptive Technologies_DT Strategy': string;
    'Disruptive Technologies_DT StrategyURL': string;
    'Disruptive Technologies_DT Yr': string;
    'PS Digital Skills & Innovation Strategy_DSI': number;
    'PS Digital Skills & Innovation Strategy_Focus': number;
    'PS Digital Skills & Innovation Strategy_DSI Strategy Name': string;
    'PS Digital Skills & Innovation Strategy_DSI URL': string;
    'PS Digital Skills & Innovation Strategy_DSI Yr': number;
    'Digital Skills & Innovation_DSI': number;
    'Digital Skills & Innovation_Prog': string;
    'Digital Skills & Innovation_Use': string;
    'Digital Skills & Innovation_DSI Prg Name': string;
    'Digital Skills & Innovation_DSI Program URL': string;
    'Digital Skills & Innovation_DSI Yr': string;
    'PS Digital Skills & Innovation Institution_PSI': number;
    'PS Digital Skills & Innovation Institution_Focus': string;
    'PS Digital Skills & Innovation Institution_PSI Institution Name': string;
    'PS Digital Skills & Innovation Institution_PSI Inst URL': string;
    'PS Digital Skills & Innovation Institution_PSI Yr': string;
    'Open Source Policies adopted by the governments_OSS': number;
    'Open Source Policies adopted by the governments_OSS Policy URL': string;
    'Open Source Policies adopted by the governments_OSS Yr': number;
    'Open Source Policies adopted by the governments_OSS Gov': number;
    'Open Source Policies adopted by the governments_RD': string;
    'Open Source Policies adopted by the governments_A': number;
    'Open Source Policies adopted by the governments_P': string;
    'Open Source Policies adopted by the governments_M': string;
    'Open Source Policies adopted by the governments_OSS Loc': number;
    'Open Source Policies adopted by the governments_RD.1': string;
    'Open Source Policies adopted by the governments_A.1': string;
    'Open Source Policies adopted by the governments_P.1': string;
    'Open Source Policies adopted by the governments_M.1': string;
    'ID4D_Nat ID': number;
    'ID4D_e-ID': number;
    'Government Effectiveness_GE': number;
    'Government Effectiveness_GE est': number;
    'Government Effectiveness_GE rank': number;
    'Government Effectiveness_GE src': number;
    'Control of Corruption_CoC': number;
    'Control of Corruption_CoC est': number;
    'Control of Corruption_CoC rank': number;
    'Control of Corruption_CoC src': number;
    CPI_CPI: number;
    'GTMI > Expert opinion for weights_Code': string;
    'GTMI > Expert opinion for weights_Grp': string;
    'GTMI > Expert opinion for weights_GTMI': number;
    'Core Gov Systems_CGSI': number;
    'Public Services_PSDI': number;
    'Citizen Engage_CEI': number;
    'GovTech Enablers_GTEI': number;
}
